imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
# Uncomment then next line if you have problems using an oracle database with mapbender.
#   - { resource: oracle.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    fallback_locale: en

framework:
    translator: { fallbacks: ['%fallback_locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    default_locale:  '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_httponly: true
        cookie_secure: '%cookie_secure%'
        cookie_lifetime: '%cookie_lifetime%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        fom: '%fom%'
    form_themes: ['FOMCoreBundle:Form:fields.html.twig']


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                path: '%database_path%'
                user: '%database_user%'
                password: '%database_password%'
                persistent: true
                charset:  UTF8
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: true
    filters:
        cssrewrite: ~
        sass: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
    router:
        annotations: false

# FOM Manager Configuration
fom_manager:
    route_prefix: /manager

# FOM User Configuration
fom_user:
    selfregister: false
    reset_password: true
    max_registration_time: 1
    max_reset_time: 1
    mail_from_address: wizard@oz.net
    mail_from_name: Wizard of Oz
    profile_entity: FOM\UserBundle\Entity\BasicProfile
    profile_formtype: FOM\UserBundle\Form\Type\BasicProfileType
    profile_template: FOMUserBundle:User:basic_profile.html.twig
    self_registration_groups:
        - Self Registered
        - Demo Group

    # Allow to create user log table on the fly if the table doesn't exits.
    # Default: true
    auto_create_log_table: false

    # Time between to check login tries
    login_check_log_time: "-5 minutes"

    # Login attemps before delay starts
    login_attempts_before_delay: 3

    # Login delay after all attemps are failed
    login_delay_after_fail: 5 # Seconds

# OWSProxy Configuration
ows_proxy3_core:
    logging: '%ows_proxy3_logging%'
    obfuscate_client_ip: '%ows_proxy3_obfuscate_client_ip%'
    proxy:
        host: '%ows_proxy3_host%'
        port: '%ows_proxy3_port%'
        connecttimeout: '%ows_proxy3_connecttimeout%'
        timeout: '%ows_proxy3_timeout%'
        user: '%ows_proxy3_user%'
        password: '%ows_proxy3_password%'
        noproxy: '%ows_proxy3_noproxy%'
        checkssl: true

# Mapbender Configuration
mapbender_core: ~
